packages:
  - packages/*

onlyBuiltDependencies:
  - '@heroui/shared-utils'
  - '@playwright/browser-chromium'
  - '@swc/core'
  - core-js
  - core-js-pure
  - esbuild
  - sharp
patchedDependencies:
  '@docusaurus/tsconfig': patches/@docusaurus__tsconfig.patch
  react-colorful: patches/react-colorful.patch
