export const SVG_TAGS: { [tagKey: string]: string } = {
  svg: "svg",
  g: "g",
  circle: "circle",
  ellipse: "ellipse",
  line: "line",
  polyline: "polyline",
  polygon: "polygon",
  rect: "rect",
  path: "path",
  text: "text",
  tspan: "tspan",
  textPath: "textPath",
  image: "image",
  use: "use",
  defs: "defs",
  clipPath: "clipPath",
  mask: "mask",
  pattern: "pattern",
  linearGradient: "linearGradient",
  radialGradient: "radialGradient",
  filter: "filter",
  symbol: "symbol",
  a: "a",
  metadata: "metadata",
  desc: "desc",
  title: "title",
};
